[package]
name = "pkh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.32"
bitcoin_hashes = "0.14" # Check for the latest version
hex = "0.4"
secp256k1 = "0.28"

